on: workflow_dispatch
jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
       - name: set variable
         run: echo "VAR1="jestem VAR1" >> $GITHUB_ENV
       - name: print variable
         run: echo "VAR1 ma wartość: $VAR1"
    job2:
      runs-on: ubuntu-latest
      outputs:
        result: ${{ steps.set-output.outputs.result }}
      steps:
        - name: Generate Output
          id: set-output
          run: echo "result=Cześć z Joba 'job2'!" >> $GITHUB_OUTPUT
    job3:
      runs-on: ubuntu-latest
      needs: job2
      steps:
        - name: Use output from previous job
          run: echo "The output from previous job is: ${{ needs.job2.outputs.result }}
        
      
